# Bitbucket connector test configuration
name: "Bitbucket Connector Test"
description: "End-to-end test of Bitbucket connector sync functionality with incremental deletion testing"

connector:
  name: "bitbucket_test"
  type: "bitbucket"
  auth_fields:
    username: "${BITBUCKET_USERNAME}"
    app_password: "${BITBUCKET_APP_PASSWORD}"
  config_fields:
    openai_model: "gpt-5"
    # post_create_sleep_seconds: 7  # Optional: wait N seconds after creation before first sync

test_flow:
  steps:
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion

# Entity configuration
entity_count: 3  # Number of entities to create for testing

deletion:
  # Phase 1: Partial deletion
  partial_delete_count: 1  # Number of entities to delete during partial deletion
  
  # Verification settings
  verify_partial_deletion: true
  verify_remaining_entities: true
  verify_complete_deletion: true

collection:
  name_template: "monke-{connector_type}-test-{timestamp}"
  description: "Test collection for {connector_type} connector"

verification:
  score_threshold: 0.1
  max_retries: 3
  retry_delay_seconds: 5

# Test-specific configuration
test_config:
  workspace: "${BITBUCKET_WORKSPACE}"  # Optional, defaults to username
  repo_slug: "monke-test-repo"  # Repository name for testing
