# Google Drive connector test configuration
name: "Google Drive Connector Test"
description: "End-to-end test of Google Drive connector sync functionality with incremental deletion testing"

connector:
  name: "google_drive_test"
  type: "google_drive"
  auth_fields:
    access_token: "${GOOGLE_DRIVE_ACCESS_TOKEN}"
  config_fields:
    openai_model: "gpt-5"
    # post_create_sleep_seconds: 7  # Optional: wait N seconds after creation before first sync

test_flow:
  steps:
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion

# Entity configuration
entity_count: 3  # Number of entities to create for testing

deletion:
  # Phase 1: Partial deletion
  partial_delete_count: 1  # Number of entities to delete during partial deletion
  
  # Verification settings
  verify_partial_deletion: true
  verify_remaining_entities: true
  verify_complete_deletion: true

collection:
  name_template: "monke-{connector_type}-test-{timestamp}"
  description: "Test collection for {connector_type} connector"

verification:
  score_threshold: 0.1
  max_retries: 3
  retry_delay_seconds: 5

# Test-specific configuration
test_config:
  file_types: ["document", "spreadsheet", "text"]  # Types of files to create
